### ISSUE TITLE
Why using wakelock and not wakelock_plus

### ISSUE THREAD

**Issue by armanhadifatah** [itsSagarBro/modern_player#1]
wakelock hasn't been updated for over 16 month you should use wakelock_plus

**Comment by itsSagarBro** [comment]
Thanks for the submitting issue, I have already implemented "wakelock_plus" and will release that in 1-2 days.

**Comment by itsSagarBro** [comment]
Hello @armanhadifatah 

Thank you for raising the concern about the wakelock dependency. I wanted to inform you that in the latest release of our package, we've addressed this by replacing wakelock with wakelock_plus. This update ensures better compatibility and more recent support for wake lock functionality.

Additionally, based on your feedback, we've also introduced callback function options. This enhancement offers more flexibility and control, allowing users to define custom callbacks as needed.

We greatly appreciate your input, and your feedback has been instrumental in improving our package. If you have any further suggestions or questions, please don't hesitate to let us know. Your engagement helps us make this package even better for the community!

Thank you for your support and involvement! 🚀 #modern_player #Flutter #Update
