### ISSUE TITLE
Get all YouTube qualities

### ISSUE THREAD

**Issue by mayman007** [itsSagarBro/modern_player#2]
I realize that muxed streams only have 720p, 360p, and 144p, but -If my understanding is right- you can get video-only stream and combine it with audio-only stream to get other qualities. It would be much better than just having these 3 qualities.

**Comment by itsSagarBro** [comment]
Yes! I am working on that and also working on getting subtitles from videos.

**Comment by mayman007** [comment]
Thank you! This package is a lifesaver for me and it will be perfect when it's completed.

**Comment by itsSagarBro** [comment]
Thank you so much for your kind words! We're thrilled that modern_player has been a lifesaver for you, and we're committed to making it even better.

Your feedback is incredibly valuable to us, and if you're finding the package helpful, we'd greatly appreciate your support by leaving a like on pub.dev. Your endorsement will help more developers discover and benefit from modern_player.

If there's anything specific you'd love to see or any feature you're eagerly anticipating, feel free to share. Your input helps shape the future of modern_player, and we're here to make it the perfect fit for your needs.

Thank you once again for your support and encouragement! 🌟🚀 #modern_player #Flutter #Support

**Comment by itsSagarBro** [comment]
Hi @mayman007 

Thank you for your feedback and suggestion! I'm pleased to inform you that the feature you requested has been implemented in modern_player 0.1.0. You can now work with video-only streams and combine them with audio-only streams to access additional qualities beyond 720p, 360p, and 144p.

Feel free to give it a try and let me know if you have any more feedback or if there's anything else I can assist you with!
