### ISSUE TITLE
Configuring the default quality

### ISSUE THREAD

**Issue by mayman007** [itsSagarBro/modern_player#3]
It would be better to have a way to configure the default quality that the videos are gonna play at without the need for the user to change it every time. 
Like the videoQualityPriority [here](https://pub.dev/packages/pod_player#configure-pod-player) for example.

**Comment by itsSagarBro** [comment]
Hey! @mayman007 Thank you for the feedback, I will surely work on this feature and will release it in the next update.

**Comment by kvenn** [comment]
I'd also like to request default subtitle and audio tracks. They're generally non-deterministic, so might need some matching criteria (like finding the track titled "English").

**Comment by itsSagarBro** [comment]
@mayman007 We have added the quality selector in dev branch, you can use it now. Thank you for the patient and supporting this package.
